/* PYTHON·LAB — Advanced challenges. */

export const advancedChallenges = [
{
  id: "a01", track: "Functions", difficulty: "Advanced", title: "Calculator Functions",
  brief: `Write four functions — <code>add(a, b)</code>, <code>subtract(a, b)</code>, <code>multiply(a, b)</code>, <code>divide(a, b)</code> — each RETURNING the result. divide must return the string <code>Cannot divide by zero</code> when b is 0.`,
  tasks: ["Each function returns its result (2 decimal places are NOT required).", "divide(5, 0) → 'Cannot divide by zero'."],
  starter: `# define add, subtract, multiply, divide here\n`,
  hints: ["Each function is two lines: def and return.", "For divide, check if b == 0 first.", "def divide(a, b):\n    if b == 0:\n        return \"Cannot divide by zero\"\n    return a / b"],
  solution: `def add(a, b):\n    return a + b\n\ndef subtract(a, b):\n    return a - b\n\ndef multiply(a, b):\n    return a * b\n\ndef divide(a, b):\n    if b == 0:\n        return "Cannot divide by zero"\n    return a / b`,
  defaultInputs: {},
  tests: [
    { inputs: {}, prelude: `print(add(10, 4))\nprint(subtract(10, 4))\nprint(multiply(10, 4))\nprint(divide(10, 4))\nprint(divide(5, 0))`, expected: `14\n6\n40\n2.5\nCannot divide by zero` },
    { inputs: {}, prelude: `print(add(-2, 2))\nprint(multiply(0, 99))\nprint(divide(9, 3))`, expected: `0\n0\n3.0` },
  ],
},
{
  id: "a02", track: "Functions", difficulty: "Advanced", title: "Recursion: Factorial & Sum",
  brief: `Write two recursive functions: <code>factorial(n)</code> returning n!, and <code>sum_to(n)</code> returning 1+2+…+n.`,
  tasks: ["Both must use recursion (no loops).", "Base cases first!"],
  starter: `# Write recursive functions factorial(n) and sum_to(n).\n# The tests will call them with a few values.\n`,
  hints: ["factorial(n) = n * factorial(n-1) with factorial(0) = 1.", "sum_to(n) = n + sum_to(n-1) with sum_to(0) = 0.", "def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n\ndef sum_to(n):\n    if n == 0:\n        return 0\n    return n + sum_to(n - 1)"],
  solution: `def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n\ndef sum_to(n):\n    if n == 0:\n        return 0\n    return n + sum_to(n - 1)`,
  defaultInputs: {},
  requires: ["factorial"],
  tests: [
    { inputs: {}, prelude: `print(factorial(5))\nprint(sum_to(10))\nprint(factorial(0))\nprint(sum_to(0))`, expected: `120\n55\n1\n0` },
  ],
},
{
  id: "a03", track: "Advanced", difficulty: "Advanced", title: "Student Class",
  brief: `Create a <code>Student</code> class storing <code>name</code> and a list of <code>grades</code>. Add methods <code>average()</code> (returns the mean) and <code>passed()</code> (returns True when average ≥ 75).`,
  tasks: ["__init__(self, name, grades).", "average() returns a number.", "passed() returns a boolean."],
  starter: `class Student:\n    # your code\n    pass\n`,
  solution: `class Student:\n    def __init__(self, name, grades):\n        self.name = name\n        self.grades = grades\n\n    def average(self):\n        return sum(self.grades) / len(self.grades)\n\n    def passed(self):\n        return self.average() >= 75`,
  hints: ["Store the values in __init__ as self.name and self.grades.", "average() can return sum(self.grades) / len(self.grades).", 'class Student:\n    def __init__(self, name, grades):\n        self.name = name\n        self.grades = grades\n\n    def average(self):\n        return sum(self.grades) / len(self.grades)\n\n    def passed(self):\n        return self.average() >= 75'],
  defaultInputs: {},
  tests: [
    { inputs: {}, prelude: `s = Student("Maria", [88, 92, 79])\nprint(s.average())\nprint(s.passed())\nt = Student("Mark", [60, 65])\nprint(t.average())\nprint(t.passed())`, expected: `86.33333333333333\nTrue\n62.5\nFalse` },
  ],
},
{
  id: "a04", track: "Advanced", difficulty: "Advanced", title: "Bank Account Class",
  brief: `Create a <code>BankAccount</code> class with <code>owner</code> and <code>balance</code> (starting at the given value). Methods: <code>deposit(amount)</code> adds money, <code>withdraw(amount)</code> subtracts but refuses (returns False) when funds are insufficient, otherwise True.`,
  tasks: ["deposit always succeeds and returns None (no return needed).", "withdraw returns False if amount > balance, else subtracts and returns True."],
  starter: `class BankAccount:\n    # your code\n    pass\n`,
  solution: `class BankAccount:\n    def __init__(self, owner, balance):\n        self.owner = owner\n        self.balance = balance\n\n    def deposit(self, amount):\n        self.balance += amount\n\n    def withdraw(self, amount):\n        if amount > self.balance:\n            return False\n        self.balance -= amount\n        return True`,
  hints: ["__init__(self, owner, balance) stores both.", "In withdraw: if amount > self.balance: return False.", 'class BankAccount:\n    def __init__(self, owner, balance):\n        self.owner = owner\n        self.balance = balance\n\n    def deposit(self, amount):\n        self.balance += amount\n\n    def withdraw(self, amount):\n        if amount > self.balance:\n            return False\n        self.balance -= amount\n        return True'],
  defaultInputs: {},
  tests: [
    { inputs: {}, prelude: `acct = BankAccount("Maria", 100)\nacct.deposit(50)\nprint(acct.balance)\nprint(acct.withdraw(200))\nprint(acct.withdraw(120))\nprint(acct.balance)`, expected: `150\nFalse\nTrue\n30` },
  ],
},
{
  id: "a05", track: "Advanced", difficulty: "Advanced", title: "Binary Search",
  brief: `Write <code>binary_search(sorted_list, target)</code> returning the index of target, or -1 if absent. The list is sorted ascending.`,
  tasks: ["Classic low/high/while loop.", "Return -1 when not found."],
  starter: `def binary_search(items, target):\n    # your code\n    pass\n`,
  solution: `def binary_search(items, target):\n    low, high = 0, len(items) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if items[mid] == target:\n            return mid\n        elif items[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1`,
  hints: ["Track low = 0 and high = len(items) - 1.", "mid = (low + high) // 2; compare items[mid] with target.", "def binary_search(items, target):\n    low, high = 0, len(items) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if items[mid] == target:\n            return mid\n        elif items[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1"],
  defaultInputs: {},
  tests: [
    { inputs: {}, prelude: `data = [1, 3, 5, 7, 9, 11]\nprint(binary_search(data, 7))\nprint(binary_search(data, 1))\nprint(binary_search(data, 11))\nprint(binary_search(data, 4))`, expected: `3\n0\n5\n-1` },
  ],
},
{
  id: "a06", track: "Advanced", difficulty: "Advanced", title: "Bubble Sort",
  brief: `Implement <code>bubble_sort(items)</code> that returns a NEW sorted list (ascending) without using sorted() or .sort().`,
  tasks: ["Compare neighbours and swap when out of order.", "Must not modify the input list; return a new one."],
  starter: `def bubble_sort(items):\n    # your code\n    pass\n`,
  solution: `def bubble_sort(items):\n    result = list(items)\n    for i in range(len(result)):\n        for j in range(len(result) - 1 - i):\n            if result[j] > result[j + 1]:\n                result[j], result[j + 1] = result[j + 1], result[j]\n    return result`,
  hints: ["Copy first: result = list(items).", "Two nested loops: for i in range(len(result)): for j in range(len(result) - 1 - i):", "def bubble_sort(items):\n    result = list(items)\n    for i in range(len(result)):\n        for j in range(len(result) - 1 - i):\n            if result[j] > result[j + 1]:\n                result[j], result[j + 1] = result[j + 1], result[j]\n    return result"],
  defaultInputs: {},
  forbidden: ["sorted", "\\.sort"],
  tests: [
    { inputs: {}, prelude: `data = [5, 2, 9, 1, 7]\nprint(bubble_sort(data))\nprint(data)`, expected: `[1, 2, 5, 7, 9]\n[5, 2, 9, 1, 7]` },
    { inputs: {}, prelude: `print(bubble_sort([3]))`, expected: `[3]` },
  ],
},
{
  id: "a07", track: "Advanced", difficulty: "Advanced", title: "Matrix Sum",
  brief: `Given a nested list <code>matrix</code> (list of lists of numbers), print the total sum of all values.`,
  tasks: ["Loop rows, then values — or use a comprehension.", "Print only the number."],
  starter: `# Variables provided: matrix\n# Write your solution here.\n`,
  hints: ["for row in matrix: gives you each inner list.", "sum(row) adds one row; accumulate the row sums.", "total = 0\nfor row in matrix:\n    total += sum(row)\nprint(total)"],
  solution: `total = 0\nfor row in matrix:\n    total += sum(row)\nprint(total)`,
  defaultInputs: {"matrix": [[1, 2, 3], [4, 5, 6], [7, 8, 9]]},
  tests: [
    { inputs: { matrix: [[1, 2, 3], [4, 5, 6], [7, 8, 9]] }, expected: `45` },
    { inputs: { matrix: [[10], [20, 30]] }, expected: `60` },
  ],
},
{
  id: "a08", track: "Advanced", difficulty: "Advanced", title: "Safe Input Parser",
  brief: `The list <code>texts</code> mixes numbers and junk. Print the double of each valid number, and <code>Skipped</code> for invalid entries — using try/except.`,
  tasks: ["int(text) raises ValueError on junk.", "Handle every entry without crashing."],
  starter: `# Variables provided: texts\n# Write your solution here.\n`,
  hints: ["Wrap the conversion in try: / except ValueError:.", "Print inside the try when it works, inside except when not.", 'for text in texts:\n    try:\n        print(int(text) * 2)\n    except ValueError:\n        print("Skipped")'],
  solution: `for text in texts:\n    try:\n        print(int(text) * 2)\n    except ValueError:\n        print("Skipped")`,
  defaultInputs: {"texts": ["10", "5", "abc", "3", "1x"]},
  requires: ["except"],
  tests: [
    { inputs: { texts: ["10", "5", "abc", "3", "1x"] }, expected: `20\n10\nSkipped\n6\nSkipped` },
    { inputs: { texts: ["7"] }, expected: `14` },
  ],
},
{
  id: "a09", track: "Advanced", difficulty: "Advanced", title: "Comprehension Power",
  brief: `Using ONE list comprehension each, create: <code>squares</code> (x² for 1..n), <code>evens</code> (even numbers 1..n), and <code>upper_names</code> (names in caps). Print all three lists.`,
  tasks: ["All three must be built with comprehensions.", "squares for n=5 → [1, 4, 9, 16, 25]."],
  starter: `# Variables provided: n, names\n# Write your solution here.\n`,
  hints: ["[x * x for x in range(1, n + 1)].", "Add if x % 2 == 0 for the evens.", "squares = [x * x for x in range(1, n + 1)]\nevens = [x for x in range(1, n + 1) if x % 2 == 0]\nupper_names = [name.upper() for name in names]\nprint(squares)\nprint(evens)\nprint(upper_names)"],
  solution: `squares = [x * x for x in range(1, n + 1)]\nevens = [x for x in range(1, n + 1) if x % 2 == 0]\nupper_names = [name.upper() for name in names]\nprint(squares)\nprint(evens)\nprint(upper_names)`,
  defaultInputs: {"n": 5, "names": ["maria", "john", "ana"]},
  requires: ["for .* in .* if|\\[.*for .*in"],
  tests: [
    { inputs: { n: 5, names: ["maria", "john", "ana"] }, expected: `[1, 4, 9, 16, 25]\n[2, 4]\n['MARIA', 'JOHN', 'ANA']` },
  ],
},
{
  id: "a10", track: "Advanced", difficulty: "Advanced", title: "Generator of Squares",
  brief: `Write a generator function <code>squares(n)</code> that yields x² for x from 1 to n. Print the values with a loop, then print the list(gen) of a fresh call.`,
  tasks: ["Must use yield.", "For n=4 → 1, 4, 9, 16."],
  starter: `def squares(n):\n    # your code\n    pass\n`,
  solution: `def squares(n):\n    for x in range(1, n + 1):\n        yield x * x`,
  hints: ["Loop inside the function and yield x * x.", "for value in squares(4): prints them one at a time.", "def squares(n):\n    for x in range(1, n + 1):\n        yield x * x\n\nfor value in squares(4):\n    print(value)\n\nprint(list(squares(4)))"],
  defaultInputs: {},
  requires: ["yield"],
  tests: [
    { inputs: {}, prelude: `for value in squares(4):\n    print(value)\nprint(list(squares(3)))`, expected: `1\n4\n9\n16\n[1, 4, 9]` },
  ],
},
{
  id: "a11", track: "Advanced", difficulty: "Advanced", title: "Top Word",
  brief: `Find the most frequent word in <code>sentence</code> and print it followed by its count: <code>the: 3</code>.`,
  tasks: ["Case-insensitive.", "If there is a tie, any most-frequent word is accepted (tests use a unique winner)."],
  starter: `# Variables provided: sentence\n# Write your solution here.\n`,
  hints: ["Lowercase, split, then count with a dictionary.", "max(counts, key=counts.get) finds the key with the highest count.", 'counts = {}\nfor word in sentence.lower().split():\n    counts[word] = counts.get(word, 0) + 1\nbest = max(counts, key=counts.get)\nprint(f"{best}: {counts[best]}")'],
  solution: `counts = {}\nfor word in sentence.lower().split():\n    counts[word] = counts.get(word, 0) + 1\n\nbest = max(counts, key=counts.get)\nprint(f"{best}: {counts[best]}")`,
  defaultInputs: {"sentence": "the cat sat on the mat with the dog"},
  tests: [
    { inputs: { sentence: "the cat sat on the mat with the dog" }, expected: `the: 3` },
    { inputs: { sentence: "go go python" }, expected: `go: 2` },
  ],
},
{
  id: "a12", track: "Advanced", difficulty: "Advanced", title: "JSON Round Trip",
  brief: `Convert the dictionary <code>product</code> to a JSON string and back. Print the JSON string, then print the restored price × stock.`,
  tasks: ["import json; use dumps and loads.", "Second line prints a number."],
  starter: `import json\n\nproduct = {"name": "coffee", "price": 3.5, "stock": 4}\n\n`,
  solution: `import json\n\ntext = json.dumps(product)\nprint(text)\n\nback = json.loads(text)\nprint(back["price"] * back["stock"])`,
  hints: ["text = json.dumps(product) gives the string.", "back = json.loads(text) gives the dictionary again.", 'import json\n\nproduct = {"name": "coffee", "price": 3.5, "stock": 4}\n\ntext = json.dumps(product)\nprint(text)\n\nback = json.loads(text)\nprint(back["price"] * back["stock"])'],
  defaultInputs: {"product": {"name": "coffee", "price": 3.5, "stock": 4}},
  tests: [
    { inputs: { product: { name: "coffee", price: 3.5, stock: 4 } }, expected: `{"name": "coffee", "price": 3.5, "stock": 4}\n14.0` },
    { inputs: { product: { name: "tea", price: 2.0, stock: 10 } }, expected: `{"name": "tea", "price": 2.0, "stock": 10}\n20.0` },
  ],
},
{
  id: "a13", track: "Advanced", difficulty: "Advanced", title: "Inheritance Zoo",
  brief: `Create <code>Animal</code> with a <code>speak()</code> method returning <code>... makes a sound</code>. Create <code>Dog</code> and <code>Cat</code> subclasses overriding speak() to return <code>Woof!</code> and <code>Meow!</code> respectively. Print speak() for a Dog and a Cat.`,
  tasks: ["Both subclasses must inherit from Animal.", "Each speak returns exactly Woof! / Meow!"],
  starter: `class Animal:\n    # your code\n    pass\n`,
  solution: `class Animal:\n    def __init__(self, name="animal"):\n        self.name = name\n\n    def speak(self):\n        return "..."\n\nclass Dog(Animal):\n    def speak(self):\n        return "Woof!"\n\nclass Cat(Animal):\n    def speak(self):\n        return "Meow!"`,
  hints: ["class Dog(Animal): inherits everything.", "Override speak() by redefining it in the subclass.", 'class Animal:\n    def speak(self):\n        return "makes a sound"\n\nclass Dog(Animal):\n    def speak(self):\n        return "Woof!"\n\nclass Cat(Animal):\n    def speak(self):\n        return "Meow!"\n\ndog = Dog()\ncat = Cat()\nprint(dog.speak())\nprint(cat.speak())'],
  defaultInputs: {},
  tests: [
    { inputs: {}, prelude: `print(Dog().speak())\nprint(Cat().speak())\nprint(isinstance(Dog(), Animal))`, expected: `Woof!\nMeow!\nTrue` },
  ],
},
{
  id: "a14", track: "Advanced", difficulty: "Advanced", title: "Timing Decorator",
  brief: `Write a decorator <code>announce</code> that prints <code>→ Starting</code> before the function runs and <code>✓ Done</code> after. Apply it to a function <code>task()</code> that prints <code>Working...</code>, then call task().`,
  tasks: ["Three lines of output in order: → Starting / Working... / ✓ Done."],
  starter: `def announce(func):\n    # your code\n    pass\n`,
  solution: `def announce(func):\n    def wrapper():\n        print("→ Starting")\n        func()\n        print("✓ Done")\n    return wrapper\n\n@announce\ndef task():\n    print("Working...")`,
  hints: ["Define wrapper() inside announce, call func() in the middle.", "return wrapper at the end of announce.", 'def announce(func):\n    def wrapper():\n        print("→ Starting")\n        func()\n        print("✓ Done")\n    return wrapper\n\n@announce\ndef task():\n    print("Working...")\n\ntask()'],
  defaultInputs: {},
  requires: ["@"],
  tests: [
    { inputs: {}, prelude: `task()`, expected: `→ Starting\nWorking...\n✓ Done` },
  ],
},
{
  id: "a15", track: "Advanced", difficulty: "Advanced", title: "Password Strength",
  brief: `Rate the password in <code>password</code>: print <code>Weak</code> (fewer than 8 chars), <code>Medium</code> (8+ chars, only letters or only digits) or <code>Strong</code> (8+ chars with both letters and digits).`,
  tasks: [".isalpha() and .isdigit() help classify.", "Mixed and 8+ chars → Strong."],
  starter: `# Variables provided: password\n# Write your solution here.\n`,
  hints: ["Check length first.", "letters = any(ch.isalpha() for ch in password), digits = any(ch.isdigit() for ch in password).", 'if len(password) < 8:\n    print("Weak")\nelif password.isalpha() or password.isdigit():\n    print("Medium")\nelse:\n    print("Strong")'],
  solution: `if len(password) < 8:\n    print("Weak")\nelif password.isalpha() or password.isdigit():\n    print("Medium")\nelse:\n    print("Strong")`,
  defaultInputs: {"password": "python123"},
  tests: [
    { inputs: { password: "python123" }, expected: `Strong` },
    { inputs: { password: "short1" }, expected: `Weak` },
    { inputs: { password: "abcdefgh" }, expected: `Medium` },
    { inputs: { password: "12345678" }, expected: `Medium` },
  ],
},
{
  id: "a16", track: "Advanced", difficulty: "Advanced", title: "Flatten a Matrix",
  brief: `Flatten the nested list <code>matrix</code> into a single list and print it, keeping order.`,
  tasks: ["[[1,2],[3,4]] → [1, 2, 3, 4].", "Loop or comprehension both fine."],
  starter: `# Variables provided: matrix\n# Write your solution here.\n`,
  hints: ["Loop over rows and extend the result.", "Or: [value for row in matrix for value in row].", "flat = []\nfor row in matrix:\n    for value in row:\n        flat.append(value)\nprint(flat)"],
  solution: `flat = []\nfor row in matrix:\n    for value in row:\n        flat.append(value)\nprint(flat)`,
  defaultInputs: {"matrix": [[1, 2], [3, 4], [5]]},
  tests: [
    { inputs: { matrix: [[1, 2], [3, 4], [5]] }, expected: `[1, 2, 3, 4, 5]` },
    { inputs: { matrix: [[], [7]] }, expected: `[7]` },
  ],
},
{
  id: "a17", track: "Advanced", difficulty: "Advanced", title: "Running Total",
  brief: `Print a running total of the list <code>numbers</code>: one line per value showing the cumulative sum, like <code>Running total: 5</code>.`,
  tasks: ["n lines for n values.", "Line i shows the sum of the first i values."],
  starter: `# Variables provided: numbers\n# Write your solution here.\n`,
  hints: ["Keep an accumulator that grows each turn.", "Print after adding the current value.", "total = 0\nfor n in numbers:\n    total += n\n    print(f\"Running total: {total}\")"],
  solution: `total = 0\nfor n in numbers:\n    total += n\n    print(f"Running total: {total}")`,
  defaultInputs: {"numbers": [5, 3, 8, 2]},
  tests: [
    { inputs: { numbers: [5, 3, 8, 2] }, expected: `Running total: 5\nRunning total: 8\nRunning total: 16\nRunning total: 18` },
    { inputs: { numbers: [10] }, expected: `Running total: 10` },
  ],
},
{
  id: "a18", track: "Advanced", difficulty: "Advanced", title: "Group by First Letter",
  brief: `Group the words in the list <code>words</code> by their first letter into a dictionary and print each group as <code>a: ['apple', 'avocado']</code>.`,
  tasks: ["Keys are first letters (lowercase).", "Values are lists in original order; print the dictionary items sorted by key."],
  starter: `# Variables provided: words\n# Write your solution here.\n`,
  solution: `groups = {}\nfor word in words:\n    groups.setdefault(word[0], []).append(word)\n\nfor letter in sorted(groups):\n    print(f"{letter}: {groups[letter]}")`,
  hints: ["groups = {} then groups.setdefault(word[0], []).append(word).", "Loop over sorted(groups) when printing.", 'groups = {}\nfor word in words:\n    groups.setdefault(word[0], []).append(word)\n\nfor letter in sorted(groups):\n    print(f"{letter}: {groups[letter]}")'],
  defaultInputs: {"words": ["apple", "banana", "avocado", "cherry", "blueberry"]},
  tests: [
    { inputs: { words: ["apple", "banana", "avocado", "cherry", "blueberry"] }, expected: `a: ['apple', 'avocado']\nb: ['banana', 'blueberry']\nc: ['cherry']` },
  ],
},
{
  id: "a19", track: "Advanced", difficulty: "Advanced", title: "Caesar Cipher",
  brief: `Encrypt <code>text</code> by shifting each letter forward by <code>shift</code> positions in the alphabet (wrap around z→a). Print the encrypted text.`,
  tasks: ["Only letters shift; spaces and symbols stay.", "Case is preserved."],
  starter: `# Shift each letter of text forward by shift (wrap z→a).\n# Keep case and non-letters unchanged.\n`,
  hints: ["For lowercase: chr((ord(ch) - 97 + shift) % 26 + 97).", "Handle uppercase separately with 65.", "result = \"\"\nfor ch in text:\n    if ch.islower():\n        result += chr((ord(ch) - 97 + shift) % 26 + 97)\n    elif ch.isupper():\n        result += chr((ord(ch) - 65 + shift) % 26 + 65)\n    else:\n        result += ch\nprint(result)"],
  solution: `result = ""\nfor ch in text:\n    if ch.islower(): result += chr((ord(ch) - 97 + shift) % 26 + 97)\n    elif ch.isupper(): result += chr((ord(ch) - 65 + shift) % 26 + 65)\n    else: result += ch\nprint(result)`,
  defaultInputs: {"text": "abc xyz", "shift": 3},
  tests: [
    { inputs: { text: "abc xyz", shift: 3 }, expected: `def abc` },
    { inputs: { text: "Hello, World!", shift: 1 }, expected: `Ifmmp, Xpsme!` },
  ],
},
{
  id: "a20", track: "Advanced", difficulty: "Advanced", title: "Grade Report",
  brief: `Build a full report from the records list <code>students</code>: per student <code>Name: avg</code> (1 decimal) and a final line <code>Top: Name</code> (highest average).`,
  tasks: ["One line per student plus the Top line.", "avg = sum(grades) / len(grades)."],
  starter: `# Compute each student's average, print each Name: avg,\n# then print the Top: line.`,
  hints: ["Compute each average into a dict: averages[name] = ...", "max(averages, key=averages.get) finds the top student.", 'averages = {}\nfor s in students:\n    averages[s["name"]] = sum(s["grades"]) / len(s["grades"])\n\nfor name, avg in averages.items():\n    print(f"{name}: {avg:.1f}")\nprint(f"Top: {max(averages, key=averages.get)}")'],
  solution: `averages = {}\nfor s in students:\n    averages[s["name"]] = sum(s["grades"]) / len(s["grades"])\n\nfor name, avg in averages.items(): print(f"{name}: {avg:.1f}")\nprint(f"Top: {max(averages, key=averages.get)}")`,
  defaultInputs: {"students": [{"name": "Maria", "grades": [88, 92, 79]}, {"name": "John", "grades": [75, 81, 90]}, {"name": "Ana", "grades": [95, 89]}]},
  tests: [
    { inputs: { students: [{ name: "Maria", grades: [88, 92, 79] }, { name: "John", grades: [75, 81, 90] }, { name: "Ana", grades: [95, 89] }] }, expected: `Maria: 86.3\nJohn: 82.0\nAna: 92.0\nTop: Ana` },
  ],
},
/*APPEND*/
]
