/* PYTHON·LAB — Beginner challenges. */

export const beginnerChallenges = [
{
  id: "b01", track: "Fundamentals", difficulty: "Beginner", title: "Personal Introduction",
  brief: `Create three variables — <code>name</code>, <code>age</code> and <code>city</code> — and print exactly:`,
  tasks: ["Create <code>name</code>, <code>age</code>, <code>city</code> with the sample values.", "Print one sentence: <code>My name is John, I am 20 years old and I live in Manila.</code>"],
  starter: `# print your sentence here\n`,
  hints: ["Use an f-string to combine the variables with text.", 'Start the line with print(f" and put the variables inside { }.', 'print(f"My name is {name}, I am {age} years old and I live in {city}.")'],
  solution: `print(f"My name is {name}, I am {age} years old and I live in {city}.")`,
  defaultInputs: {"name": "John", "age": 20, "city": "Manila"},
  tests: [{ inputs: { name: "John", age: 20, city: "Manila" }, expected: `My name is John, I am 20 years old and I live in Manila.` }],
},
{
  id: "b02", track: "Fundamentals", difficulty: "Beginner", title: "Celsius to Fahrenheit",
  brief: `Convert the temperature in variable <code>celsius</code> to Fahrenheit and print the result with one decimal.`,
  tasks: ["Read <code>celsius</code> (provided).", "Fahrenheit = celsius × 9 / 5 + 32.", "Print like <code>37.0 C = 98.6 F</code>."],
  starter: `# convert and print\n`,
  hints: ["The formula is celsius * 9 / 5 + 32.", "Use an f-string with :.1f to force one decimal.", 'print(f"{celsius} C = {celsius * 9 / 5 + 32} F")'],
  solution: `fahrenheit = celsius * 9 / 5 + 32\nprint(f"{celsius:.1f} C = {fahrenheit} F")`,
  defaultInputs: {"celsius": 37},
  tests: [
    { inputs: { celsius: 37 }, expected: `37.0 C = 98.6 F` },
    { inputs: { celsius: 0 }, expected: `0.0 C = 32.0 F` },
    { inputs: { celsius: 100 }, expected: `100.0 C = 212.0 F` },
  ],
},
{
  id: "b03", track: "Fundamentals", difficulty: "Beginner", title: "Rectangle Area",
  brief: `Compute the area and perimeter of a rectangle from variables <code>width</code> and <code>height</code>.`,
  tasks: ["Area = width × height.", "Perimeter = 2 × (width + height).", "Print <code>Area: 20</code> then <code>Perimeter: 18</code> for width=4, height=5."],
  starter: `# print area and perimeter\n`,
  hints: ["Area uses *, perimeter uses + inside parentheses.", "Two print() lines are enough.", "print(f\"Area: {width * height}\") and print(f\"Perimeter: {2 * (width + height)}\")"],
  solution: `area = width * height\nperimeter = 2 * (width + height)\n\nprint(f"Area: {area}")\nprint(f"Perimeter: {perimeter}")`,
  defaultInputs: {"width": 4, "height": 5},
  tests: [
    { inputs: { width: 4, height: 5 }, expected: `Area: 20\nPerimeter: 18` },
    { inputs: { width: 7, height: 3 }, expected: `Area: 21\nPerimeter: 20` },
  ],
},
{
  id: "b04", track: "Fundamentals", difficulty: "Beginner", title: "Even or Odd",
  brief: `Print <code>Even</code> or <code>Odd</code> depending on the number in <code>number</code>.`,
  tasks: ["A number is even when the remainder after dividing by 2 is 0.", "Print exactly one word: Even or Odd."],
  starter: `# your check here\n`,
  hints: ["The modulo operator % gives the remainder of a division.", "Check whether number % 2 equals 0.", "if number % 2 == 0:\n    print(\"Even\")\nelse:\n    print(\"Odd\")"],
  solution: `if number % 2 == 0:\n    print("Even")\nelse:\n    print("Odd")`,
  defaultInputs: {"number": 7},
  tests: [
    { inputs: { number: 7 }, expected: `Odd` },
    { inputs: { number: 10 }, expected: `Even` },
    { inputs: { number: 0 }, expected: `Even` },
  ],
},
{
  id: "b05", track: "Fundamentals", difficulty: "Beginner", title: "Shopping Receipt",
  brief: `Given <code>price</code> and <code>quantity</code>, print a tiny receipt with the total (2 decimals).`,
  tasks: ["Total = price × quantity.", "Print <code>Total: 14.97</code> for price 4.99, quantity 3."],
  starter: `# Variables provided: price, quantity\n# Write your solution here.\n`,
  hints: ["Multiply the two variables.", "Format with :.2f to always show two decimals.", 'print(f"Total: {price * quantity:.2f}")'],
  solution: `total = price * quantity\nprint(f"Total: {total:.2f}")`,
  defaultInputs: {"price": 4.99, "quantity": 3},
  tests: [
    { inputs: { price: 4.99, quantity: 3 }, expected: `Total: 14.97` },
    { inputs: { price: 2.5, quantity: 4 }, expected: `Total: 10.00` },
  ],
},
{
  id: "b06", track: "Fundamentals", difficulty: "Beginner", title: "String Shout",
  brief: `Make a greeting loud: print the value of <code>name</code> in UPPERCASE followed by <code>!!!</code>.`,
  tasks: ["Convert to upper case with .upper().", "Print like <code>MARIA!!!</code>."],
  starter: `# Variables provided: name\n# Write your solution here.\n`,
  hints: ["Strings have an .upper() method.", "Strings can be glued with + or an f-string.", 'print(name.upper() + "!!!")'],
  solution: `print(f"{name.upper()}!!!")`,
  defaultInputs: {"name": "Maria"},
  tests: [
    { inputs: { name: "Maria" }, expected: `MARIA!!!` },
    { inputs: { name: "john" }, expected: `JOHN!!!` },
  ],
},
{
  id: "b07", track: "Fundamentals", difficulty: "Beginner", title: "Swap the Values",
  brief: `The variables <code>a</code> and <code>b</code> hold numbers. Swap them and print <code>a</code> then <code>b</code> on separate lines.`,
  tasks: ["After your code, a must hold the old value of b and vice versa.", "Print a, then b — each on its own line."],
  starter: `# swap them\n`,
  hints: ["Python can swap in one line with tuple unpacking: a, b = b, a.", "Or use a temporary variable: temp = a.", "a, b = b, a\nprint(a)\nprint(b)"],
  solution: `a, b = b, a\nprint(a)\nprint(b)`,
  defaultInputs: {"a": 1, "b": 2},
  tests: [
    { inputs: { a: 1, b: 2 }, expected: `2\n1` },
    { inputs: { a: 10, b: 99 }, expected: `99\n10` },
  ],
},
{
  id: "b08", track: "Fundamentals", difficulty: "Beginner", title: "Seconds to Time",
  brief: `Convert <code>seconds</code> into minutes and remaining seconds.`,
  tasks: ["Minutes = seconds // 60 (floor division).", "Remaining seconds = seconds % 60.", "Print like <code>130 seconds = 2 min 10 sec</code>."],
  starter: `# Variables provided: seconds\n# Write your solution here.\n`,
  hints: ["// gives whole minutes, % gives the leftover.", "130 // 60 is 2 and 130 % 60 is 10.", 'print(f"{seconds} seconds = {seconds // 60} min {seconds % 60} sec")'],
  solution: `minutes = seconds // 60\nrest = seconds % 60\nprint(f"{seconds} seconds = {minutes} min {rest} sec")`,
  defaultInputs: {"seconds": 130},
  tests: [
    { inputs: { seconds: 130 }, expected: `130 seconds = 2 min 10 sec` },
    { inputs: { seconds: 60 }, expected: `60 seconds = 1 min 0 sec` },
    { inputs: { seconds: 45 }, expected: `45 seconds = 0 min 45 sec` },
  ],
},
{
  id: "b09", track: "Fundamentals", difficulty: "Beginner", title: "Name Tag",
  brief: `Build a neat name tag: print the name centered in a box line of exactly 12 characters using dashes.`,
  tasks: ["Print a line of 12 dashes.", "Print the name centered in 12 characters.", "Print the dashes line again."],
  starter: `# Variables provided: name\n# Write your solution here.\n`,
  hints: ["12 dashes can be printed with \"-\" * 12.", "Center with f\"{name:^12}\".", 'print("-" * 12)\nprint(f"{name:^12}")\nprint("-" * 12)'],
  solution: `print("-" * 12)\nprint(f"{name:^12}")\nprint("-" * 12)`,
  defaultInputs: {"name": "Maria"},
  tests: [
    { inputs: { name: "Maria" }, expected: `------------\n   Maria    \n------------` },
  ],
},
{
  id: "b10", track: "Fundamentals", difficulty: "Beginner", title: "Average Grade",
  brief: `Given the list <code>scores</code>, print the average with one decimal.`,
  tasks: ["Average = sum of scores ÷ number of scores.", "Print like <code>Average: 76.8</code>."],
  starter: `# Variables provided: scores\n# Write your solution here.\n`,
  hints: ["sum(scores) adds them all, len(scores) counts them.", "Divide the two, then format with :.1f.", 'average = sum(scores) / len(scores)\nprint(f"Average: {average:.1f}")'],
  solution: `average = sum(scores) / len(scores)\nprint(f"Average: {average:.1f}")`,
  defaultInputs: {"scores": [75, 82, 59, 91]},
  tests: [
    { inputs: { scores: [75, 82, 59, 91] }, expected: `Average: 76.8` },
    { inputs: { scores: [100, 90, 80] }, expected: `Average: 90.0` },
  ],
},
{
  id: "b11", track: "Control Flow", difficulty: "Beginner", title: "Voting Age",
  brief: `Print <code>Can vote</code> if <code>age</code> is 18 or more, otherwise print <code>Cannot vote</code>.`,
  tasks: ["Use an if / else statement.", "The boundary matters: 18 itself can vote."],
  starter: `# Variables provided: age\n# Write your solution here.\n`,
  hints: ["Compare with >=  to include 18.", "if age >= 18: ... else: ...", 'if age >= 18:\n    print("Can vote")\nelse:\n    print("Cannot vote")'],
  solution: `if age >= 18:\n    print("Can vote")\nelse:\n    print("Cannot vote")`,
  defaultInputs: {"age": 17},
  tests: [
    { inputs: { age: 17 }, expected: `Cannot vote` },
    { inputs: { age: 18 }, expected: `Can vote` },
    { inputs: { age: 65 }, expected: `Can vote` },
  ],
},
{
  id: "b12", track: "Control Flow", difficulty: "Beginner", title: "Largest of Three",
  brief: `Print the largest of the three numbers <code>a</code>, <code>b</code>, <code>c</code>.`,
  tasks: ["Print just the number.", "If several tie for largest, printing that value is still correct."],
  starter: `# Variables provided: a, b, c\n# Write your solution here.\n`,
  hints: ["Compare them with if / elif / else.", "You may also use the built-in max(a, b, c).", "print(max(a, b, c))"],
  solution: `largest = a\nif b > largest:\n    largest = b\nif c > largest:\n    largest = c\nprint(largest)`,
  defaultInputs: {"a": 12, "b": 45, "c": 7},
  tests: [
    { inputs: { a: 12, b: 45, c: 7 }, expected: `45` },
    { inputs: { a: 99, b: 8, c: 71 }, expected: `99` },
    { inputs: { a: 5, b: 5, c: 9 }, expected: `9` },
  ],
},
{
  id: "b13", track: "Control Flow", difficulty: "Beginner", title: "Grade Letter",
  brief: `Print the letter grade for <code>score</code>: 90+ → A, 80+ → B, 70+ → C, 60+ → D, otherwise F.`,
  tasks: ["Use if / elif / else in the right order.", "Print only the letter."],
  starter: `# Variables provided: score\n# Write your solution here.\n`,
  hints: ["Check from the highest grade down.", "The first True elif wins, so order matters.", 'if score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelif score >= 70:\n    print("C")\nelif score >= 60:\n    print("D")\nelse:\n    print("F")'],
  solution: `if score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelif score >= 70:\n    print("C")\nelif score >= 60:\n    print("D")\nelse:\n    print("F")`,
  defaultInputs: {"score": 83},
  tests: [
    { inputs: { score: 83 }, expected: `B` },
    { inputs: { score: 95 }, expected: `A` },
    { inputs: { score: 60 }, expected: `D` },
    { inputs: { score: 12 }, expected: `F` },
  ],
},
{
  id: "b14", track: "Control Flow", difficulty: "Beginner", title: "Countdown",
  brief: `Print a countdown from <code>start</code> down to 1, then print <code>Lift off!</code>.`,
  tasks: ["One number per line, descending.", "Finish with the exact line Lift off!"],
  starter: `# Variables provided: start\n# Write your solution here.\n`,
  hints: ["range(0, start, -1) counts down: 5, 4, 3, 2, 1.", "Or use while start > 0: ... start -= 1.", 'for i in range(0, start, -1):\n    print(i)\nprint("Lift off!")'],
  solution: `for i in range(start, 0, -1):\n    print(i)\nprint("Lift off!")`,
  defaultInputs: {"start": 5},
  tests: [
    { inputs: { start: 5 }, expected: `5\n4\n3\n2\n1\nLift off!` },
    { inputs: { start: 3 }, expected: `3\n2\n1\nLift off!` },
  ],
},
{
  id: "b15", track: "Control Flow", difficulty: "Beginner", title: "Sum 1 to N",
  brief: `Print the sum of all whole numbers from 1 up to and including <code>n</code>.`,
  tasks: ["For n = 10 the answer is 55.", "Print only the number."],
  starter: `# Variables provided: n\n# Write your solution here.\n`,
  hints: ["Use a loop or the formula n * (n + 1) // 2.", "Accumulate with total += i.", "total = 0\nfor i in range(1, n + 1):\n    total += i\nprint(total)"],
  solution: `total = 0\nfor i in range(1, n + 1):\n    total += i\nprint(total)`,
  defaultInputs: {"n": 10},
  tests: [
    { inputs: { n: 10 }, expected: `55` },
    { inputs: { n: 1 }, expected: `1` },
    { inputs: { n: 100 }, expected: `5050` },
  ],
},
{
  id: "b16", track: "Control Flow", difficulty: "Beginner", title: "Multiplication Table",
  brief: `Print the multiplication table of <code>number</code> from 1 to 10, one per line, formatted like <code>3 x 1 = 3</code>.`,
  tasks: ["10 lines, from ×1 to ×10.", "Exact format: <code>{number} x {i} = {result}</code>."],
  starter: `# Variables provided: number\n# Write your solution here.\n`,
  hints: ["Loop i over range(1, 11).", "Use an f-string for the format.", 'for i in range(1, 11):\n    print(f"{number} x {i} = {number * i}")'],
  solution: `for i in range(1, 11):\n    print(f"{number} x {i} = {number * i}")`,
  defaultInputs: {"number": 3},
  tests: [
    { inputs: { number: 3 }, expected: `3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15\n3 x 6 = 18\n3 x 7 = 21\n3 x 8 = 24\n3 x 9 = 27\n3 x 10 = 30` },
    { inputs: { number: 7 }, expected: `7 x 1 = 7\n7 x 2 = 14\n7 x 3 = 21\n7 x 4 = 28\n7 x 5 = 35\n7 x 6 = 42\n7 x 7 = 49\n7 x 8 = 56\n7 x 9 = 63\n7 x 10 = 70` },
  ],
},
{
  id: "b17", track: "Control Flow", difficulty: "Beginner", title: "Password Check",
  brief: `The variable <code>password</code> holds the user's attempt. Print <code>Access granted</code> when it equals <code>python123</code>, otherwise <code>Access denied</code>.`,
  tasks: ["Exact string comparison with ==.", "Only one of the two lines is printed."],
  starter: `# Variables provided: password\n# Write your solution here.\n`,
  hints: ["Compare strings with ==.", "The secret is python123.", 'if password == "python123":\n    print("Access granted")\nelse:\n    print("Access denied")'],
  solution: `if password == "python123":\n    print("Access granted")\nelse:\n    print("Access denied")`,
  defaultInputs: {"password": "hello123"},
  tests: [
    { inputs: { password: "hello123" }, expected: `Access denied` },
    { inputs: { password: "python123" }, expected: `Access granted` },
  ],
},
{
  id: "b18", track: "Control Flow", difficulty: "Beginner", title: "FizzBuzz Lite",
  brief: `Print numbers 1 to <code>n</code>, but print <code>Fizz</code> instead of multiples of 3 and <code>Buzz</code> instead of multiples of 5 (FizzBuzz for both).`,
  tasks: ["One line per number from 1 to n.", "Multiples of both get FizzBuzz."],
  starter: `# Variables provided: n\n# Write your solution here.\n`,
  hints: ["Check divisibility by 15 first, then 3, then 5.", "number % 3 == 0 detects multiples of 3.", 'for i in range(1, n + 1):\n    if i % 15 == 0:\n        print("FizzBuzz")\n    elif i % 3 == 0:\n        print("Fizz")\n    elif i % 5 == 0:\n        print("Buzz")\n    else:\n        print(i)'],
  solution: `for i in range(1, n + 1):\n    if i % 15 == 0:\n        print("FizzBuzz")\n    elif i % 3 == 0:\n        print("Fizz")\n    elif i % 5 == 0:\n        print("Buzz")\n    else:\n        print(i)`,
  defaultInputs: {"n": 15},
  tests: [
    { inputs: { n: 15 }, expected: `1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz` },
    { inputs: { n: 5 }, expected: `1\n2\nFizz\n4\nBuzz` },
  ],
},
{
  id: "b19", track: "Control Flow", difficulty: "Beginner", title: "Discount Price",
  brief: `Apply a percentage discount: given <code>price</code> and <code>discount_percent</code>, print the final price with 2 decimals.`,
  tasks: ["Final = price − price × percent / 100.", "Print like <code>Final: 80.00</code>."],
  starter: `# Variables provided: discount_percent, price\n# Write your solution here.\n`,
  hints: ["10% of 100 is 100 * 10 / 100.", "Compute the reduction, subtract it, format with :.2f.", 'final_price = price - price * discount_percent / 100\nprint(f"Final: {final_price:.2f}")'],
  solution: `final_price = price - price * discount_percent / 100\nprint(f"Final: {final_price:.2f}")`,
  defaultInputs: {"price": 100, "discount_percent": 20},
  tests: [
    { inputs: { price: 100, discount_percent: 20 }, expected: `Final: 80.00` },
    { inputs: { price: 59.99, discount_percent: 10 }, expected: `Final: 53.99` },
  ],
},
{
  id: "b20", track: "Control Flow", difficulty: "Beginner", title: "Right Triangle",
  brief: `Print a right triangle of stars, <code>n</code> rows tall: row 1 has 1 star, row 2 has 2 stars, etc.`,
  tasks: ["n lines total.", "Row i contains i stars, e.g. n=4 → *, **, ***, ****."],
  starter: `# Variables provided: n\n# Write your solution here.\n`,
  hints: ["Loop i over range(1, n + 1).", "Print \"*\" * i each turn.", 'for i in range(1, n + 1):\n    print("*" * i)'],
  solution: `for i in range(1, n + 1):\n    print("*" * i)`,
  defaultInputs: {"n": 4},
  tests: [
    { inputs: { n: 4 }, expected: `*\n**\n***\n****` },
    { inputs: { n: 2 }, expected: `*\n**` },
  ],
},
/*APPEND*/
]
