/* PYTHON·LAB — Debugging practice: broken programs to find & fix. */

export const debugChallenges = [
{
  id: "d01", track: "Fundamentals", difficulty: "Beginner", bugType: "Syntax error", title: "The Missing Colon",
  task: "Fix the program so it prints all numbers correctly.",
  broken: `numbers = [1, 2, 3, 4]\n\nfor number in numbers\n    print(number)`,
  expected: `1\n2\n3\n4`,
  hints: ["Read the error message — which line does it point to?", "Loops, ifs and functions all end their first line with a special character.", "Add the missing colon : after numbers"],
  solution: `numbers = [1, 2, 3, 4]\n\nfor number in numbers:\n    print(number)`,
},
{
  id: "d02", track: "Fundamentals", difficulty: "Beginner", bugType: "Indentation error", title: "Inside or Outside?",
  task: "The program should print 'You are an adult' twice. Fix the indentation.",
  broken: `age = 21\n\nif age >= 18:\nprint("You are an adult")\nprint("You are an adult")`,
  expected: `You are an adult\nYou are an adult`,
  hints: ["Python uses indentation to know which lines belong to the if.", "Lines inside a block are indented 4 spaces.", 'if age >= 18:\n    print("You are an adult")\n    print("You are an adult")'],
  solution: `age = 21\n\nif age >= 18:\n    print("You are an adult")\n    print("You are an adult")`,
},
{
  id: "d03", track: "Fundamentals", difficulty: "Beginner", bugType: "Logical error", title: "Off-by-One Total",
  task: "The program should print the sum 1+2+3+4+5 = 15, but it prints the wrong number. Find the logic bug.",
  broken: `total = 1\nfor i in range(1, 6):\n    total = i\nprint(total)`,
  expected: `15`,
  hints: ["The accumulator must keep its old value each turn.", "Look closely at what total is set to inside the loop.", "total = 0\nfor i in range(1, 6):\n    total += i\nprint(total)"],
  solution: `total = 0\nfor i in range(1, 6):\n    total += i\nprint(total)`,
},
{
  id: "d04", track: "Fundamentals", difficulty: "Beginner", bugType: "Variable error", title: "Undefined Name",
  task: "The program should greet the user, but it crashes. Fix the variable problem.",
  broken: `name = "Maria"\n\nprint("Hello, " + username)`,
  expected: `Hello, Maria`,
  hints: ["Read the NameError: which name is not defined?", "The variable is called name, not username.", 'print("Hello, " + name)'],
  solution: `name = "Maria"\n\nprint("Hello, " + name)`,
},
{
  id: "d05", track: "Fundamentals", difficulty: "Beginner", bugType: "Runtime error", title: "The Type Trouble",
  task: "The program should print the age next year (21), but it crashes with a TypeError.",
  broken: `age = "20"\nnext_year = age + 1\nprint(next_year)`,
  expected: `21`,
  hints: ["Strings and numbers cannot be added together.", "Convert the text to a number with int().", "age = int(\"20\")\nnext_year = age + 1\nprint(next_year)"],
  solution: `age = "20"\nnext_year = int(age) + 1\nprint(next_year)`,
},
{
  id: "d06", track: "Control Flow", difficulty: "Beginner", bugType: "Logical error", title: "Infinite Loop",
  task: "The while loop never ends — the sandbox will stop it. Fix it so it prints 1 to 5 and finishes.",
  broken: `count = 1\nwhile count <= 5:\n    print(count)`,
  expected: `1\n2\n3\n4\n5`,
  hints: ["For the loop to end, something must make count <= 5 false.", "Nothing ever changes count inside the loop.", "count = 1\nwhile count <= 5:\n    print(count)\n    count += 1"],
  solution: `count = 1\nwhile count <= 5:\n    print(count)\n    count += 1`,
},
{
  id: "d07", track: "Control Flow", difficulty: "Beginner", bugType: "Syntax error", title: "Quotes Gone Wrong",
  task: "The program should print: She said \"hi\" — but the quotes confuse Python. Fix it.",
  broken: `print("She said "hi"")`,
  expected: `She said "hi"`,
  hints: ["The string ends at the first inner quote.", "Mix quote types: single quotes outside, double inside.", `print('She said "hi"')`],
  solution: `print('She said "hi"')`,
},
{
  id: "d08", track: "Control Flow", difficulty: "Intermediate", bugType: "Logical error", title: "The Grade That Lies",
  task: "A score of 95 should give grade A, but this program prints B. Fix the conditions.",
  broken: `score = 95\n\nif score >= 80:\n    print("B")\nelif score >= 90:\n    print("A")`,
  expected: `A`,
  hints: ["elif only runs when the earlier if was False.", "95 matches the first condition, so the A branch is never reached.", 'if score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")'],
  solution: `score = 95\n\nif score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")`,
},
{
  id: "d09", track: "Control Flow", difficulty: "Intermediate", bugType: "Runtime error", title: "Index Out of Range",
  task: "Print every score in the list without crashing.",
  broken: `scores = [70, 85, 90]\n\nfor i in range(len(scores) + 1):\n    print(scores[i])`,
  expected: `70\n85\n90`,
  hints: ["range(len(scores) + 1) produces one index too many.", "Indexes go from 0 to len - 1.", "for i in range(len(scores)):\n    print(scores[i])"],
  solution: `scores = [70, 85, 90]\n\nfor i in range(len(scores)):\n    print(scores[i])`,
},
{
  id: "d10", track: "Data Structures", difficulty: "Intermediate", bugType: "Logical error", title: "The Vanishing Sort",
  task: "The program should print the sorted list [1, 2, 3, 4], but it prints None. Fix it.",
  broken: `numbers = [4, 2, 3, 1]\nresult = numbers.sort()\nprint(result)`,
  expected: `[1, 2, 3, 4]`,
  hints: [".sort() reorders the list in place and returns None.", "Either print numbers after sorting, or use sorted(numbers).", "numbers = [4, 2, 3, 1]\nnumbers.sort()\nprint(numbers)"],
  solution: `numbers = [4, 2, 3, 1]\nnumbers.sort()\nprint(numbers)`,
},
{
  id: "d11", track: "Data Structures", difficulty: "Intermediate", bugType: "Runtime error", title: "The Missing Key",
  task: "Print the student's grade without crashing, even though 'grade' is not in the dictionary (print None).",
  broken: `student = {"name": "John", "age": 20}\n\nprint(student["grade"])`,
  expected: `None`,
  hints: ["Accessing a missing key raises KeyError.", ".get() returns None instead of crashing.", 'print(student.get("grade"))'],
  solution: `student = {"name": "John", "age": 20}\n\nprint(student.get("grade"))`,
},
{
  id: "d12", track: "Functions", difficulty: "Intermediate", bugType: "Logical error", title: "The Silent Function",
  task: "The program should print the square of 5 (that is 25), but it prints None. Fix the function.",
  broken: `def square(n):\n    print(n * n)\n\nresult = square(5)\nprint(result)`,
  expected: `25`,
  hints: ["A function that prints but does not return gives None back.", "Replace print with return inside square.", "def square(n):\n    return n * n\n\nresult = square(5)\nprint(result)"],
  solution: `def square(n):\n    return n * n\n\nresult = square(5)\nprint(result)`,
},
{
  id: "d13", track: "Functions", difficulty: "Advanced", bugType: "Variable error", title: "The Leaking Variable",
  task: "The function should compute 12.0 as tax from 100, but crashes. Fix it.",
  broken: `def tax(amount):\n    return amount * tax_rate\n\nprint(tax(100))\ntax_rate = 0.12`,
  expected: `12.0`,
  hints: ["tax_rate is used before it exists anywhere.", "Define tax_rate before calling the function (or pass it as a parameter).", "tax_rate = 0.12\n\ndef tax(amount):\n    return amount * tax_rate\n\nprint(tax(100))"],
  solution: `tax_rate = 0.12\n\ndef tax(amount):\n    return amount * tax_rate\n\nprint(tax(100))`,
},
{
  id: "d14", track: "Advanced", difficulty: "Advanced", bugType: "Logical error", title: "The Recursion That Never Lands",
  task: "countdown(3) should print 3, 2, 1 and stop. Right now it recurses forever (the sandbox will stop it).",
  broken: `def countdown(n):\n    print(n)\n    countdown(n - 1)\n\ncountdown(3)`,
  expected: `3\n2\n1`,
  hints: ["Every recursion needs a base case that stops the calls.", "What happens when n reaches 0? Nothing stops it.", "def countdown(n):\n    if n == 0:\n        return\n    print(n)\n    countdown(n - 1)\n\ncountdown(3)"],
  solution: `def countdown(n):\n    if n == 0:\n        return\n    print(n)\n    countdown(n - 1)\n\ncountdown(3)`,
},
{
  id: "d15", track: "Advanced", difficulty: "Advanced", bugType: "Runtime error", title: "The Crashing Divider",
  task: "Print the result of dividing each pair, but dividing by zero must print 'Division skipped' instead of crashing.",
  broken: `pairs = [(10, 2), (8, 0), (9, 3)]\n\nfor a, b in pairs:\n    print(a / b)`,
  expected: `5.0\nDivision skipped\n3.0`,
  hints: ["ZeroDivisionError will crash the program.", "Wrap the division in try / except.", 'for a, b in pairs:\n    try:\n        print(a / b)\n    except ZeroDivisionError:\n        print("Division skipped")'],
  solution: `pairs = [(10, 2), (8, 0), (9, 3)]\n\nfor a, b in pairs:\n    try:\n        print(a / b)\n    except ZeroDivisionError:\n        print("Division skipped")`,
},
];
