/* PYTHON·LAB — Intermediate challenges. */

export const intermediateChallenges = [
{
  id: "i01", track: "Control Flow", difficulty: "Intermediate", title: "Even Number Finder",
  brief: `The list <code>numbers</code> is given. Loop through it and print only the even numbers.`,
  tasks: ["Loop through the list.", "Print each even number on its own line."],
  starter: `# Variables provided: numbers\n# Write your solution here.\n`,
  hints: ["Use a for loop over numbers.", "Check evenness with the modulo operator: n % 2 == 0.", "for n in numbers:\n    if n % 2 == 0:\n        print(n)"],
  solution: `for n in numbers:\n    if n % 2 == 0:\n        print(n)`,
  defaultInputs: {"numbers": [1, 2, 3, 4, 5, 6]},
  requires: ["for|while"],
  tests: [
    { inputs: { numbers: [1, 2, 3, 4, 5, 6] }, expected: `2\n4\n6` },
    { inputs: { numbers: [10, 15, 20] }, expected: `10\n20` },
    { inputs: { numbers: [7, 9] }, expected: `` },
  ],
},
{
  id: "i02", track: "Control Flow", difficulty: "Intermediate", title: "List Statistics",
  brief: `Print three lines for the list <code>numbers</code>: <code>Min: x</code>, <code>Max: y</code>, <code>Average: z</code> (average with 2 decimals).`,
  tasks: ["Do the min/max yourself with a loop, or use built-ins.", "Average formatted like <code>Average: 5.50</code>."],
  starter: `# Variables provided: numbers\n# Write your solution here.\n`,
  hints: ["min() and max() do the first two in one call each.", "sum(numbers) / len(numbers) is the average.", 'print(f"Min: {min(numbers)}")\nprint(f"Max: {max(numbers)}")\nprint(f"Average: {sum(numbers) / len(numbers):.2f}")'],
  solution: `print(f"Min: {min(numbers)}")\nprint(f"Max: {max(numbers)}")\nprint(f"Average: {sum(numbers) / len(numbers):.2f}")`,
  defaultInputs: {"numbers": [3, 8, 1, 9, 6]},
  tests: [
    { inputs: { numbers: [3, 8, 1, 9, 6] }, expected: `Min: 1\nMax: 9\nAverage: 5.40` },
    { inputs: { numbers: [10, 20] }, expected: `Min: 10\nMax: 20\nAverage: 15.00` },
  ],
},
{
  id: "i03", track: "Control Flow", difficulty: "Intermediate", title: "Vowel Counter",
  brief: `Count how many vowels (a, e, i, o, u) appear in the string <code>text</code> and print <code>Vowels: N</code>.`,
  tasks: ["Case-insensitive: A counts too.", "Print exactly <code>Vowels: N</code>."],
  starter: `# Variables provided: text\n# Write your solution here.\n`,
  hints: ["Loop over the string character by character.", "Lowercase the text first: text.lower().", 'count = 0\nfor ch in text.lower():\n    if ch in "aeiou":\n        count += 1\nprint(f"Vowels: {count}")'],
  solution: `count = 0\nfor ch in text.lower():\n    if ch in "aeiou":\n        count += 1\nprint(f"Vowels: {count}")`,
  defaultInputs: {"text": "Programming is fun"},
  tests: [
    { inputs: { text: "Programming is fun" }, expected: `Vowels: 5` },
    { inputs: { text: "AEIOU" }, expected: `Vowels: 5` },
    { inputs: { text: "xyz" }, expected: `Vowels: 0` },
  ],
},
{
  id: "i04", track: "Control Flow", difficulty: "Intermediate", title: "Palindrome Check",
  brief: `Print <code>Palindrome</code> if <code>word</code> reads the same backwards, otherwise <code>Not palindrome</code>.`,
  tasks: ["A palindrome is symmetric, like racecar.", "Ignore case: Anna is a palindrome."],
  starter: `# Variables provided: word\n# Write your solution here.\n`,
  hints: ["word[::-1] reverses a string.", "Compare the lowercased word with its reverse.", 'if word.lower() == word.lower()[::-1]:\n    print("Palindrome")\nelse:\n    print("Not palindrome")'],
  solution: `if word.lower() == word.lower()[::-1]:\n    print("Palindrome")\nelse:\n    print("Not palindrome")`,
  defaultInputs: {"word": "racecar"},
  tests: [
    { inputs: { word: "racecar" }, expected: `Palindrome` },
    { inputs: { word: "Anna" }, expected: `Palindrome` },
    { inputs: { word: "python" }, expected: `Not palindrome` },
  ],
},
{
  id: "i05", track: "Control Flow", difficulty: "Intermediate", title: "Prime or Not",
  brief: `Print <code>Prime</code> if <code>n</code> is a prime number, otherwise <code>Not prime</code>.`,
  tasks: ["A prime is only divisible by 1 and itself.", "1 is NOT prime. 2 is prime."],
  starter: `# Variables provided: n\n# Write your solution here.\n`,
  hints: ["Check divisors from 2 up to n-1; if any divides n, it is not prime.", "The % operator detects divisibility.", 'is_prime = n > 1\nfor i in range(2, n):\n    if n % i == 0:\n        is_prime = False\n        break\nprint("Prime" if is_prime else "Not prime")'],
  solution: `is_prime = n > 1\nfor i in range(2, n):\n    if n % i == 0:\n        is_prime = False\n        break\nprint("Prime" if is_prime else "Not prime")`,
  defaultInputs: {"n": 13},
  tests: [
    { inputs: { n: 13 }, expected: `Prime` },
    { inputs: { n: 12 }, expected: `Not prime` },
    { inputs: { n: 2 }, expected: `Prime` },
    { inputs: { n: 1 }, expected: `Not prime` },
  ],
},
{
  id: "i06", track: "Control Flow", difficulty: "Intermediate", title: "Word Counter",
  brief: `Count the words in the sentence <code>sentence</code> and print <code>Words: N</code>.`,
  tasks: ["Words are separated by spaces.", "Multiple spaces in a row must not break the count."],
  starter: `# Variables provided: sentence\n# Write your solution here.\n`,
  hints: [".split() with no arguments splits on any whitespace and drops empties.", "len() counts list items.", 'print(f"Words: {len(sentence.split())}")'],
  solution: `print(f"Words: {len(sentence.split())}")`,
  defaultInputs: {"sentence": "Python makes coding fun"},
  tests: [
    { inputs: { sentence: "Python makes coding fun" }, expected: `Words: 4` },
    { inputs: { sentence: "hello" }, expected: `Words: 1` },
    { inputs: { sentence: "  spaced   out   words " }, expected: `Words: 3` },
  ],
},
{
  id: "i07", track: "Control Flow", difficulty: "Intermediate", title: "Second Largest",
  brief: `Print the second largest value in the list <code>numbers</code>.`,
  tasks: ["Duplicates allowed; e.g. [5, 5, 3] → second largest is 3? No — distinct values: 5 and 3, so print 3.", "Print only the number."],
  starter: `# Variables provided: numbers\n# Write your solution here.\n`,
  hints: ["sorted(numbers) gives ascending order; [-2] is the second to last.", "Or remove duplicates first with set().", "unique = sorted(set(numbers))\nprint(unique[-2])"],
  solution: `unique = sorted(set(numbers))\nprint(unique[-2])`,
  defaultInputs: {"numbers": [12, 45, 2, 45, 39]},
  tests: [
    { inputs: { numbers: [12, 45, 2, 45, 39] }, expected: `39` },
    { inputs: { numbers: [1, 2] }, expected: `1` },
    { inputs: { numbers: [7, 7, 7, 3] }, expected: `3` },
  ],
},
{
  id: "i08", track: "Data Structures", difficulty: "Intermediate", title: "Unique List",
  brief: `Print the list <code>items</code> without duplicates, keeping the original order, like <code>['a', 'b', 'c', 'd']</code>.`,
  tasks: ["Duplicates removed, first occurrence kept.", "Print the resulting list (a normal print of a list is fine)."],
  starter: `# Variables provided: items\n# Write your solution here.\n`,
  hints: ["Loop and only append items not already in the result.", "The in operator checks list membership.", "result = []\nfor item in items:\n    if item not in result:\n        result.append(item)\nprint(result)"],
  solution: `result = []\nfor item in items:\n    if item not in result:\n        result.append(item)\nprint(result)`,
  defaultInputs: {"items": ["a", "b", "a", "c", "b", "d"]},
  tests: [
    { inputs: { items: ["a", "b", "a", "c", "b", "d"] }, expected: `['a', 'b', 'c', 'd']` },
    { inputs: { items: [1, 1, 1] }, expected: `[1]` },
  ],
},
{
  id: "i09", track: "Data Structures", difficulty: "Intermediate", title: "Gradebook Average",
  brief: `The dictionary <code>grades</code> maps student names to scores. Print each student as <code>Name: 88</code> and finally <code>Class average: 86.0</code>.`,
  tasks: ["One line per student in <code>Name: score</code> form.", "Last line: <code>Class average: X</code> with one decimal."],
  starter: `# Variables provided: grades\n# Write your solution here.\n`,
  hints: [".items() gives (key, value) pairs in a loop.", "Average = sum of values ÷ number of values.", 'for name, grade in grades.items():\n    print(f"{name}: {grade}")\naverage = sum(grades.values()) / len(grades)\nprint(f"Class average: {average:.1f}")'],
  solution: `for name, grade in grades.items():\n    print(f"{name}: {grade}")\n\naverage = sum(grades.values()) / len(grades)\nprint(f"Class average: {average:.1f}")`,
  defaultInputs: {"grades": {"Maria": 88, "John": 92, "Ana": 78}},
  tests: [
    { inputs: { grades: { Maria: 88, John: 92, Ana: 78 } }, expected: `Maria: 88\nJohn: 92\nAna: 78\nClass average: 86.0` },
  ],
},
{
  id: "i10", track: "Data Structures", difficulty: "Intermediate", title: "Contact Book",
  brief: `Look up a name in the dictionary <code>contacts</code>. Print <code>Name: number</code>, or <code>Not found</code> if the name is missing.`,
  tasks: ["Use the key <code>query</code>.", "Missing keys must not crash the program."],
  starter: `# Variables provided: contacts, query\n# Write your solution here.\n`,
  hints: [".get(key) returns None for missing keys — or .get(key, default).", "Check with an if/else on the result.", 'number = contacts.get(query)\nif number:\n    print(f"{query}: {number}")\nelse:\n    print("Not found")'],
  solution: `if query in contacts:\n    print(f"{query}: {contacts[query]}")\nelse:\n    print("Not found")`,
  defaultInputs: {"contacts": {"Maria": "0917-111", "John": "0918-222"}, "query": "John"},
  tests: [
    { inputs: { contacts: { Maria: "0917-111", John: "0918-222" }, query: "John" }, expected: `John: 0918-222` },
    { inputs: { contacts: { Maria: "0917-111" }, query: "Bob" }, expected: `Not found` },
  ],
},
{
  id: "i11", track: "Control Flow", difficulty: "Intermediate", title: "Factorial (Loop)",
  brief: `Compute the factorial of <code>n</code> (n! = 1 × 2 × … × n) with a loop and print it.`,
  tasks: ["0! = 1 by definition.", "Print only the number."],
  starter: `# Variables provided: n\n# Write your solution here.\n`,
  hints: ["Start result at 1 and multiply by every i from 2 to n.", "range(2, n + 1) covers the factors.", "result = 1\nfor i in range(2, n + 1):\n    result *= i\nprint(result)"],
  solution: `result = 1\nfor i in range(2, n + 1):\n    result *= i\nprint(result)`,
  defaultInputs: {"n": 5},
  tests: [
    { inputs: { n: 5 }, expected: `120` },
    { inputs: { n: 0 }, expected: `1` },
    { inputs: { n: 10 }, expected: `3628800` },
  ],
},
{
  id: "i12", track: "Control Flow", difficulty: "Intermediate", title: "Fibonacci Sequence",
  brief: `Print the first <code>count</code> Fibonacci numbers, one per line (starting 0, 1, 1, 2, 3…).`,
  tasks: ["Each number is the sum of the two before it.", "Print exactly count lines."],
  starter: `# Variables provided: count\n# Write your solution here.\n`,
  hints: ["Keep two variables a = 0, b = 1.", "Each turn: print a, then shift: a, b = b, a + b.", "a, b = 0, 1\nfor _ in range(count):\n    print(a)\n    a, b = b, a + b"],
  solution: `a, b = 0, 1\nfor _ in range(count):\n    print(a)\n    a, b = b, a + b`,
  defaultInputs: {"count": 7},
  tests: [
    { inputs: { count: 7 }, expected: `0\n1\n1\n2\n3\n5\n8` },
    { inputs: { count: 2 }, expected: `0\n1` },
  ],
},
{
  id: "i13", track: "Data Structures", difficulty: "Intermediate", title: "Shopping Cart Total",
  brief: `The list <code>cart</code> holds (name, price) tuples. Print each item as <code>name: price</code> and the grand total as <code>Total: 12.25</code>.`,
  tasks: ["One line per item.", "Total formatted with 2 decimals."],
  starter: `# Variables provided: cart\n# Write your solution here.\n`,
  hints: ["Tuples unpack in the loop: for name, price in cart:", "Accumulate a running total.", 'total = 0\nfor name, price in cart:\n    print(f"{name}: {price}")\n    total += price\nprint(f"Total: {total:.2f}")'],
  solution: `total = 0\nfor name, price in cart:\n    print(f"{name}: {price}")\n    total += price\nprint(f"Total: {total:.2f}")`,
  defaultInputs: {"cart": [["coffee", 3.5], ["tea", 2.75], ["water", 1.0]]},
  tests: [
    { inputs: { cart: [["coffee", 3.5], ["tea", 2.75], ["water", 1.0]] }, expected: `coffee: 3.5\ntea: 2.75\nwater: 1.0\nTotal: 7.25` },
  ],
},
{
  id: "i14", track: "Data Structures", difficulty: "Intermediate", title: "Reverse Words",
  brief: `Reverse the order of words in <code>sentence</code>: <code>fun is coding</code> becomes <code>coding is fun</code>.`,
  tasks: ["Split, reverse, join.", "Print only the new sentence."],
  starter: `# Variables provided: sentence\n# Write your solution here.\n`,
  hints: [".split() makes a word list; [::-1] reverses it.", '" ".join(words) glues the list back with spaces.', 'print(" ".join(sentence.split()[::-1]))'],
  solution: `words = sentence.split()\nreversed_words = words[::-1]\nprint(" ".join(reversed_words))`,
  defaultInputs: {"sentence": "fun is coding"},
  tests: [
    { inputs: { sentence: "fun is coding" }, expected: `coding is fun` },
    { inputs: { sentence: "hello world" }, expected: `world hello` },
  ],
},
{
  id: "i15", track: "Control Flow", difficulty: "Intermediate", title: "Count Letters",
  brief: `Build a frequency counter: print each letter of <code>word</code> with how many times it appears, like <code>a: 3</code>, sorted alphabetically.`,
  tasks: ["One <code>letter: count</code> line per distinct letter.", "Sort the letters alphabetically."],
  starter: `# Variables provided: word\n# Write your solution here.\n`,
  hints: ["Use a dictionary with letter as key.", "dict.get(letter, 0) + 1 is the classic counting pattern.", 'counts = {}\nfor ch in word:\n    counts[ch] = counts.get(ch, 0) + 1\nfor letter in sorted(counts):\n    print(f"{letter}: {counts[letter]}")'],
  solution: `counts = {}\nfor ch in word:\n    counts[ch] = counts.get(ch, 0) + 1\n\nfor letter in sorted(counts):\n    print(f"{letter}: {counts[letter]}")`,
  defaultInputs: {"word": "banana"},
  tests: [
    { inputs: { word: "banana" }, expected: `a: 3\nb: 1\nn: 2` },
    { inputs: { word: "abc" }, expected: `a: 1\nb: 1\nc: 1` },
  ],
},
{
  id: "i16", track: "Data Structures", difficulty: "Intermediate", title: "Passing Students",
  brief: `From the list of records <code>students</code> (dictionaries with <code>name</code> and <code>grade</code>), print <code>Name passed</code> for everyone with grade ≥ 75, in order.`,
  tasks: ["Filter with a loop or comprehension.", "Format: <code>Maria passed</code>."],
  starter: `# Variables provided: students\n# Write your solution here.\n`,
  hints: ["Each item is a dictionary: s[\"name\"], s[\"grade\"].", "Combine an if with the loop.", 'for s in students:\n    if s["grade"] >= 75:\n        print(f\'{s["name"]} passed\')'],
  solution: `for s in students:\n    if s["grade"] >= 75:\n        print(f'{s["name"]} passed')`,
  defaultInputs: {"students": [{"name": "Maria", "grade": 88}, {"name": "John", "grade": 92}, {"name": "Mark", "grade": 61}]},
  tests: [
    { inputs: { students: [{ name: "Maria", grade: 88 }, { name: "John", grade: 92 }, { name: "Mark", grade: 61 }] }, expected: `Maria passed\nJohn passed` },
    { inputs: { students: [{ name: "Ana", grade: 70 }] }, expected: `` },
  ],
},
{
  id: "i17", track: "Data Structures", difficulty: "Intermediate", title: "Sum of Digits",
  brief: `Print the sum of the digits of the number <code>n</code> (e.g. 1234 → 10).`,
  tasks: ["Work with the digits mathematically or as a string.", "Print only the sum."],
  starter: `# Variables provided: n\n# Write your solution here.\n`,
  hints: ["str(n) turns the number into a string you can loop over.", "int(ch) converts each character back to a digit.", "total = 0\nfor ch in str(n):\n    total += int(ch)\nprint(total)"],
  solution: `total = 0\nfor ch in str(n):\n    total += int(ch)\nprint(total)`,
  defaultInputs: {"n": 1234},
  tests: [
    { inputs: { n: 1234 }, expected: `10` },
    { inputs: { n: 999 }, expected: `27` },
    { inputs: { n: 5 }, expected: `5` },
  ],
},
{
  id: "i18", track: "Control Flow", difficulty: "Intermediate", title: "Inverted Pyramid",
  brief: `Print an inverted star pyramid with <code>n</code> rows: row 1 has n stars, last row has 1.`,
  tasks: ["n lines, descending star counts.", "No leading spaces needed."],
  starter: `# Variables provided: n\n# Write your solution here.\n`,
  hints: ["Loop i from n down to 1.", "range(n, 0, -1) gives n, n-1, …, 1.", 'for i in range(n, 0, -1):\n    print("*" * i)'],
  solution: `for i in range(n, 0, -1):\n    print("*" * i)`,
  defaultInputs: {"n": 5},
  tests: [
    { inputs: { n: 5 }, expected: `*****\n****\n***\n**\n*` },
    { inputs: { n: 3 }, expected: `***\n**\n*` },
  ],
},
{
  id: "i19", track: "Control Flow", difficulty: "Intermediate", title: "Leap Year",
  brief: `Print <code>Leap year</code> or <code>Not leap year</code> for the year <code>year</code>.`,
  tasks: ["Divisible by 4 → leap, except centuries.", "Centuries must be divisible by 400 (2000 yes, 1900 no)."],
  starter: `# Variables provided: year\n# Write your solution here.\n`,
  hints: ["A year is leap if year % 4 == 0 and (year % 100 != 0 or year % 400 == 0).", "Combine the checks with and / or.", 'if year % 4 == 0 and (year % 100 != 0 or year % 400 == 0):\n    print("Leap year")\nelse:\n    print("Not leap year")'],
  solution: `if year % 4 == 0 and (year % 100 != 0 or year % 400 == 0):\n    print("Leap year")\nelse:\n    print("Not leap year")`,
  defaultInputs: {"year": 2024},
  tests: [
    { inputs: { year: 2024 }, expected: `Leap year` },
    { inputs: { year: 1900 }, expected: `Not leap year` },
    { inputs: { year: 2000 }, expected: `Leap year` },
    { inputs: { year: 2023 }, expected: `Not leap year` },
  ],
},
{
  id: "i20", track: "Functions", difficulty: "Intermediate", title: "Reusable Greeting",
  brief: `Define a function <code>greet(name, greeting="Hello")</code> that RETURNS the text <code>greeting, name!</code>. The tests will call it with a few names and check the returned text.`,
  tasks: ["The function must return the string (not print it).", "Call it twice and print each result."],
  starter: `def greet(name, greeting="Hello"):\n    pass  # return the greeting string`,
  hints: ["def greet(name, greeting=\"Hello\"):", "Build the string with an f-string and return it.", 'def greet(name, greeting="Hello"):\n    return f"{greeting}, {name}!"\n\nprint(greet("Maria"))\nprint(greet("John", "Hi"))'],
  solution: `def greet(name, greeting="Hello"):\n    return f"{greeting}, {name}!"`,
  defaultInputs: {},
  tests: [
    { inputs: {}, prelude: `print(greet("Maria"))\nprint(greet("John", "Hi"))\nprint(greet("Ana", "Welcome"))`, expected: `Hello, Maria!\nHi, John!\nWelcome, Ana!` },
  ],
},
/*APPEND*/
]
